-- MySQL Script generated by MySQL Workbench
-- Wed Oct 14 10:00:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdd_blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdd_blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdd_blog` DEFAULT CHARACTER SET utf8mb4 ;
USE `bdd_blog` ;

-- -----------------------------------------------------
-- Table `bdd_blog`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_blog`.`utilisateurs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `pays` VARCHAR(64) NOT NULL,
  `date_naissance` DATE NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `genre` TINYINT NULL COMMENT '0 = She/Her, 1 = He/His, Rest = Other',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_blog`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_blog`.`posts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(64) NOT NULL,
  `message` VARCHAR(512) NOT NULL,
  `post_date` TIMESTAMP NOT NULL DEFAULT NOW(),
  `utilisateurs_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `titre_UNIQUE` (`titre` ASC),
  UNIQUE INDEX `message_UNIQUE` (`message` ASC),
  INDEX `fk_posts_utilisateurs_idx` (`utilisateurs_id` ASC),
  CONSTRAINT `fk_posts_utilisateurs`
    FOREIGN KEY (`utilisateurs_id`)
    REFERENCES `bdd_blog`.`utilisateurs` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
